{
  "openapi": "3.0.1",
  "info": {
    "version": "2.0.3",
    "title": "Watertracker API",
    "description": "API documentation for project Watertracker"
  },
  "consumes": ["application/json", "multipart/form-data"],
  "produces": ["application/json"],
  "servers": [
    {
      "url": "http://localhost:5000"
    }
  ],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "Users",
      "description": "User information endpoints"
    },
    {
      "name": "Water",
      "description": "Water information endpoints"
    }
  ],
  "paths": {
    "/auth/signup": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Such e-mail already exist",
            "content": {}
          }
        }
      }
    },
    "/auth/signin": {
      "post": {
        "tags": ["Auth"],
        "summary": "User authentication",
        "requestBody": {
          "description": "Authentication's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AuthenticationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuthenticationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "E-mail or password invalid",
            "content": {}
          }
        }
      }
    },
    "/auth/signout": {
      "post": {
        "tags": ["Auth"],
        "summary": "User logout",
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "204": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Respons message ",
                      "example": "Signout successful"
                    }
                  },
                  "example": {
                    "message": "Signout successful"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": " Not authorized",
            "content": {}
          }
        }
      }
    },
    "/users/current": {
      "get": {
        "tags": ["Users"],
        "summary": "User's information",
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserInfoResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": " Not authorized",
            "content": {}
          }
        }
      }
    },
    "/users": {
      "patch": {
        "tags": ["Users"],
        "summary": "Update user's information",
        "security": [
          {
            "Bearer": []
          }
        ],
        "requestBody": {
          "description": "Update's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserInfoRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserInfoResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": " Not authorized",
            "content": {}
          }
        }
      }
    },
    "/users/avatar": {
      "patch": {
        "tags": ["Users"],
        "summary": "Update user's avatar",
        "security": [
          {
            "Bearer": []
          }
        ],
        "requestBody": {
          "description": "Avatar image",
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "required": ["avatar"],
                "type": "object",
                "properties": {
                  "avatar": {
                    "type": "string",
                    "format": "binary",
                    "description": "User's avatar image"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "avatarURL": {
                      "type": "string",
                      "description": "Avatar URL",
                      "example": "https://res.cloudinary.com/doojzyo8d/image/upload/v1706979817/water-tracker/avatars/65b8535366f632bd6e48f05d_avatar.jpg"
                    }
                  },
                  "example": {
                    "avatarURL": "https://res.cloudinary.com/doojzyo8d/image/upload/v1706979817/water-tracker/avatars/65b8535366f632bd6e48f05d_avatar.jpg"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": " Not authorized",
            "content": {}
          }
        }
      }
    },
    "/water-rate": {
      "patch": {
        "tags": ["Water"],
        "summary": "Update user's water rate",
        "security": [
          {
            "Bearer": []
          }
        ],
        "requestBody": {
          "description": "Water rate",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "waterRate": {
                    "type": "number",
                    "description": "User water rate",
                    "example": 2000
                  }
                },
                "example": {
                  "waterRate": 2000
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "waterRate": {
                      "type": "number",
                      "description": "User water rate",
                      "example": 2000
                    }
                  },
                  "example": {
                    "waterRate": 2000
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": " Not authorized",
            "content": {}
          }
        }
      }
    },
     "/water/": {
      "post": {
        "tags": ["Water"],
        "summary": "Add water servings",
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Servings object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddWaterRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/WaterResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": " Not authorized",
            "content": {}
          }
        }
      }
    },
    "/water/{id}": {
      "patch": {
        "tags": ["Water"],
        "summary": "Update water servings ",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "type": "string",
            "description": "Servings id"
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Servings object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddWaterRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/WaterResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": " Not authorized",
            "content": {}
          }
        }
      },
      "delete": {
        "tags": ["Water"],
        "summary": "Delete water servings ",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "type": "string",
            "description": "Servings id"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/WaterResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": " Not authorized",
            "content": {}
          }
        }
      }
    },
    "/water/today/{date}": {
      "get": {
        "tags": ["Water"],
        "summary": "List of doses per day ",
        "parameters": [
          {
            "in": "path",
            "name": "date",
            "required": true,
            "type": "string",
            "description": "Date's today",
            "example": "2024-01-30T01:39:31.276Z"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/WaterResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": " Not authorized",
            "content": {}
          }
        }
      }
    },
    "/water/month/{date}": {
      "get": {
        "tags": ["Water"],
        "summary": "Information per month",
        "parameters": [
          {
            "in": "path",
            "name": "date",
            "required": true,
            "type": "string",
            "description": "Date's today",
            "example": "2024-01-30T01:39:31.276Z"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MonthWaterResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": " Not authorized",
            "content": {}
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "vitalii@gmail.com"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "1234567890"
          }
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string",
            "description": "Access token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Yjg1MzUzNjZmNjMyYmQ2ZTQ4ZjA1ZCIsImlhdCI6MTcwNjk3OTkyMSwiZXhwIjoxNzA3MDYyNzIxfQ.DXGeIrTbJhtqrnSp5ZS14BhgwwL0sFG7aqpDG2jwiDY"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "vitalii@gmail.com"
          },
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Vitalii"
          },
          "avatarURL": {
            "type": "string",
            "description": "Avatar URL",
            "example": "https://res.cloudinary.com/doojzyo8d/image/upload/v1706979817/water-tracker/avatars/65b8535366f632bd6e48f05d_avatar.jpg"
          },
          "gender": {
            "type": "string",
            "description": "User's gender",
            "example": "male"
          },
          "waterRate": {
            "type": "number",
            "description": "User water rate",
            "example": 2000
          },
          "date": {
            "type": "string",
            "description": "Registration date",
            "example": "2024-01-30T01:39:31.276Z"
          }
        },
        "example": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Yjg1MzUzNjZmNjMyYmQ2ZTQ4ZjA1ZCIsImlhdCI6MTcwNjk3OTkyMSwiZXhwIjoxNzA3MDYyNzIxfQ.DXGeIrTbJhtqrnSp5ZS14BhgwwL0sFG7aqpDG2jwiDY",
          "email": "vitalii@gmail.com",
          "name": "Vitalii",
          "avatarURL": "https://res.cloudinary.com/doojzyo8d/image/upload/v1706979817/water-tracker/avatars/65b8535366f632bd6e48f05d_avatar.jpg",
          "gender": "male",
          "waterRate": 2000,
          "date": "2024-01-30T01:39:31.276Z"
        }
      },
      "AuthenticationRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "vitalii@gmail.com"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "1234567890"
          }
        }
      },
      "AuthenticationResponse": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string",
            "description": "Access token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Yjg1MzUzNjZmNjMyYmQ2ZTQ4ZjA1ZCIsImlhdCI6MTcwNjk3OTkyMSwiZXhwIjoxNzA3MDYyNzIxfQ.DXGeIrTbJhtqrnSp5ZS14BhgwwL0sFG7aqpDG2jwiDY"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
           "example":"vitalii@gmail.com"
          },
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Vitalii"
          },
          "avatarURL": {
            "type": "string",
            "description": "Avatar URL",
            "example": "https://res.cloudinary.com/doojzyo8d/image/upload/v1706979817/water-tracker/avatars/65b8535366f632bd6e48f05d_avatar.jpg"
          },
          "gender": {
            "type": "string",
            "description": "User's gender",
            "example": "male"
          },
          "waterRate": {
            "type": "number",
            "description": "User water rate",
            "example": 2000
          },
          "date": {
            "type": "string",
            "description": "Registration date",
            "example": "2024-01-30T01:39:31.276Z"
          }
        },
        "example": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Yjg1MzUzNjZmNjMyYmQ2ZTQ4ZjA1ZCIsImlhdCI6MTcwNjk3OTkyMSwiZXhwIjoxNzA3MDYyNzIxfQ.DXGeIrTbJhtqrnSp5ZS14BhgwwL0sFG7aqpDG2jwiDY",
          "email": "vitalii@gmail.com",
          "name": "Vitalii",
          "avatarURL": "https://res.cloudinary.com/doojzyo8d/image/upload/v1706979817/water-tracker/avatars/65b8535366f632bd6e48f05d_avatar.jpg",
          "gender": "male",
          "waterRate": 2000,
          "date": "2024-01-30T01:39:31.276Z"
        }
      },
      "UpdateUserInfoRequest": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "vitalii@gmail.com"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "1234567890"
          },
          "newPassword": {
            "type": "number",
            "description": "New user's password",
            "example": "1234567890test"
          },
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Vitalii"
          },
          "gender": {
            "type": "string",
            "description": "User's gender",
            "example": "male"
          }
        },
        "example": {
          "email": "vitalii@gmail.com",
          "avatarURL": "https://res.cloudinary.com/doojzyo8d/image/upload/v1706979817/water-tracker/avatars/65b8535366f632bd6e48f05d_avatar.jpg",
          "name": "Vitalii",
          "gender": "male",
          "password": "1234567890",
          "newPassword": "1234567890test"
        }
      },
      "UserInfoResponse": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "vitalii@gmail.com"
          },
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Vitalii"
          },
          "avatarURL": {
            "type": "string",
            "description": "Avatar URL",
            "example": "https://res.cloudinary.com/doojzyo8d/image/upload/v1706979817/water-tracker/avatars/65b8535366f632bd6e48f05d_avatar.jpg"
          },
          "gender": {
            "type": "string",
            "description": "User's gender",
            "example": "male"
          },
          "waterRate": {
            "type": "number",
            "description": "User water rate",
            "example": 2000
          },
          "date": {
            "type": "string",
            "description": "Registration date",
            "example": "2024-01-30T01:39:31.276Z"
          }
        },
        "example": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Yjg1MzUzNjZmNjMyYmQ2ZTQ4ZjA1ZCIsImlhdCI6MTcwNjk3OTkyMSwiZXhwIjoxNzA3MDYyNzIxfQ.DXGeIrTbJhtqrnSp5ZS14BhgwwL0sFG7aqpDG2jwiDY",
          "email": "vitalii@gmail.com",
          "name": "Vitalii",
          "avatarURL": "https://res.cloudinary.com/doojzyo8d/image/upload/v1706979817/water-tracker/avatars/65b8535366f632bd6e48f05d_avatar.jpg",
          "gender": "male",
          "waterRate": 2000,
          "date": "2024-01-30T01:39:31.276Z"
        }
      },
       "AddWaterRequest": {
        "type": "object",
        "required": ["date", "water"],
        "properties": {
          "waterVolume": {
            "type": "number",
            "description": "Servings size",
            "example": 150
          },
          "date": {
            "type": "string",
            "description": "Date of servings addition",
            "example": "2024-01-30T01:39:31.276Z"
          }
        },
        "example": {
          "date": "2024-01-30T01:39:31.276Z",
          "waterVolume": 150
        }
      },
      "WaterResponse": {
        "type": "object",
        "properties": {
          "percentage": {
            "type": "number",
            "description": "Percentage of the daily rate",
            "example": 30
          },
          "dailyPortions": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "Servings id",
                  "example": "65b933d060bd22e993ec36a2"
                },
                "owner":{
                  "type": "string",
                  "description": "User",
                  "example": "65b6810f7a4e87117023146e"
                },
                "waterVolume": {
                  "type": "number",
                  "description": "Servings size",
                  "example": 100
                },
                "date": {
            "type": "string",
            "description": "Date of servings addition",
            "example": "2024-01-30T01:39:31.276Z"
          }
              }
            }
          }
        },
        "example": {
          "dailyPortions": [
            {
              "id": "65ba785cbd84ba65bfe31419",
              "waterVolume": 150,
              "owner": "65b6810f7a4e87117023146e",
              "data": "2024-01-30T01:39:31.276Z"
            },
            {
              "id": "65ba88d3a881baf02a126af5",
              "waterVolume": 50,
              "owner": "65b6810f7a4e87117023146e",
              "data": "2024-01-30T01:39:31.276Z"
            }
          ],
          "percentage": 10
        }
      },
      "MonthWaterResponse": {
          "month": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "date": {
                  "type": "string",
                  "description": "Registration date",
                  "example": "2024-01-30T01:39:31.276Z"
                },
                "waterRate": {
                  "type": "number",
                  "description": "User water rate",
                  "example": 2.0
                },
                "percentage": {
                  "type": "number",
                  "description": "Percentage of the daily rate",
                  "example": 10
                },
                "servings": {
                  "type": "number",
                  "description": "Quantity of servings per day",
                  "example": 2
                }
              }
            }
          },
        "example": {
          "month": [
            {
              "date": "2024-01-30T01:39:31.276Z",
              "waterRate": 2.0,
              "percentage": 90,
              "servings": 4
            },
            {
              "date": "2024-01-30T01:39:31.276Z",
              "percentage": 10,
              "waterRate": 2.0,
              "servings": 2
            }
          ]
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
